### ISSUE TITLE
postgres-12 migration required for base.sql

### ISSUE THREAD

**Issue by cs-499243** [UniversityRadioYork/MyRadio#1037]
Due to [changes in postgres 12](https://www.postgresql.org/docs/12/release-12.html#id-1.11.6.13.4) when you try to import the file [`base.sql`](../blob/master/schema/base.sql) you get `ERROR: tables declared WITH OIDS are not supported`. Because of this, [the setup](../blob/master/src/Controllers/Setup/dbschema.php#L44) just ignores the invalid code and moves past, meaning the database isn't built at all. Also not sure why the try-catch isn't doing much of anything around that.

`base.sql` has 27 instances of [`default_with_oids`](https://postgresqlco.nf/doc/en/param/default_with_oids/) in it so what can we do? We can't just not go to postgres-12 cause then the whole thing fails to run. Or at least I think that's the problem.

**Comment by mstratford** [comment]
Iirc we just deleted the oids. I don't think the oids actually did much.
