### ISSUE TITLE
The MyRadio_Timeslot with instance ID does not exist.

### ISSUE THREAD

**Issue by cs-endo** [UniversityRadioYork/MyRadio#1043]
On 2021-06-16 `The MyRadio_Timeslot with instance ID #148893 does not exist.` was logged around once every second for maybe a day or two.
On 2021-09-22 `The MyRadio_Timeslot with instance ID #148953 does not exist.` was logged around once every second for about 2 days.

Anyone know why this could be happening on these dates? And, then, how we can stop it happening again? It's very effectively filling up the error logs

**Comment by markspolakovs** [comment]
Cannot reproduce.
