### ISSUE TITLE
New users get sent email from the no-reply address, rather than the getinvolved

### ISSUE THREAD

**Issue by LordAro** [UniversityRadioYork/MyRadio#108]
At least, they will, once my upcoming prq is merged

**Comment by LordAro** [comment]
Olol. (Continuing from #574) Regardless, even then sending from a no-reply address that "seems like it's from an actual person" is still by no means unique to us

**Comment by ChrisTheBaron** [comment]
No I know, but making it so that their login details are in a separate email from `no-reply` would mean they _could_ reply to the welcome email without an issue. It's not too much work, and it would make the freshers less confused :wink:

**Comment by mstratford** [comment]
I think we've finally finished this in #808
