### ISSUE TITLE
MyRadio should prevent user from adding a training session where there is already one

### ISSUE THREAD

**Issue by ColinRoitt** [UniversityRadioYork/MyRadio#1185]
Training session times are set by the user but there is currently no validation that there are no overlaps in training sessions. This is required as we only have one off-air studio to use for training.

**Comment by Keeeeeeeen** [comment]
Should it allow two simultaneous training sessions if there's no shows on?

**Comment by ColinRoitt** [comment]
> Should it allow two simultaneous training sessions if there's no shows on?

Best to avoid as sessions are booked often well in advanced and shows could appear in the mean time. 

There's no scheduling process for checking if training is happening and shows take priority over things like this.

**Comment by michael-grace** [comment]
you could replace the schedule iframe on the add training session page with the off air studio calendar

**Comment by ColinRoitt** [comment]
> you could replace the schedule iframe on the add training session page with the off air studio calendar

damn that's actually a good idea... but is it too lazy a solution... Maybe I'll do that for now while I work on a more user-oriented fix

**Comment by ColinRoitt** [comment]
I will propose at comp meeting to up the priority of this issue as people have been double booking studios through MyRadio training slots and via the calendar.
