### ISSUE TITLE
Twig URL builder and custom properties

### ISSUE THREAD

**Issue by LloydW93** [UniversityRadioYork/MyRadio#149]
Don't work with rewrites enabled, e.g.:
module=Mail,action=send,list=n results in ?module=Mail&action=sendlist=n

**Comment by AJDurant** [comment]
Looking at the current macro, I can't actually see what is wrong with it =/
https://github.com/UniversityRadioYork/MyRadio/blob/e0c5af53cf8cc4179cb8acfecc4300741c87e0e3/src/Templates/macros.twig

**Comment by LloydW93** [comment]
Worksforme now
