### ISSUE TITLE
Api error messages (403)

### ISSUE THREAD

**Issue by Flump5281** [UniversityRadioYork/MyRadio#249]
Spit out both json and html:

{"status":403,"time":"0.011403","message":"Your API Key (7449) does not have access to this method."}<!DOCTYPE html><html><head><title>Internal Server Error | University Radio York</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><link rel="Stylesheet" type="text/css" href="//ury.org.uk/myury/css/normalise.css"><link rel="Stylesheet" type="text/css" href="//ury.org.uk/myury/css/vendor/themes/ury-purple/jquery-ui.css"><link rel="stylesheet" type="text/css" href="//ury.org.uk/myury/css/main.css"><link rel="Stylesheet" type="text/css" href="//ury.org.uk/myury/css/style.css"><script type="text/javascript" src="//ury.org.uk/myury/js/vendor/jquery-2.1.0.min.js"></script></head><body><nav id="menu" class="transBG"><a id="miniLogo" href="//ury.org.uk/myury/">MyRadio</a><ul><li><a href="//ury.org.uk/myury/
MyRadio/logout/">Logout</a></li></ul><ul id="navRight"><li><a href="//ury.org.uk/myury/
MyRadio/timeslot/?next=/api/Track/findByOptions/?options=%7B%22title%22%3A%22Winter%20Linn%22%7D" title="Click to change timeslot">29/06/2014 19:00</a></li><li><a href="//ury.org.uk/myury/
Profile/default/">Lloyd Wallis</a></li></ul></nav><ul class="php_error"></ul><header id="pageHeader" class="clearfix"><a id="logo" href="//ury.org.uk/myury/"><h1>University Radio York</h1></a></header><div id="grid" class="transBG clearfix"><header id="content-header"><h2>Internal Server Error</h2></header><div id="content-body" class="clearfix"><div class="ui-state-header"><center><p>MyRadio has encountered a problem processing this request.</p><table class='errortable' style='color:#633'><tr><td>Message: </td><td>API Error: Your API Key (7449) does not have access to this method.
Source: 90.198.254.6</td></tr><tr><td>Location: </td><td>/usr/local/www/myradio/src/PublicAPI/index.php:48</td></tr><tr><td>Trace: </td><td>#0 /usr/local/www/myradio/src/PublicAPI/index.php(162): api_error(403, 'Your API Key (7...')<br />
#1 {main}</td></tr></table></center></div><a href="javascript:history.go(-1)">Go back</a></div></div><footer id="pageFooter" class="clearfix"><div id="copyright"><p>&copy;1967-2014 University Radio York. MyRadio by <a href="mailto:webmaster@ury.org.uk" title="5">URY Computing Team</a></div></div><ul><li><a href="http://www.york.ac.uk/docs/disclaimer/disclaimer.htm">Disclaimer</a></li><li>&nbsp;<a href="http://ury.org.uk/contact/">Contact Us</a></li></ul></footer><script type="text/javascript" src="//ury.org.uk/myury/MyRadio/config.js"></script><script type="text/javascript" src="//ury.org.uk/myury/js/myury.core.js"></script><script type="text/javascript" src="//ury.org.uk/myury/js/vendor/jquery-ui-1.10.4.custom.min.js"></script><script type="text/javascript" src="//ury.org.uk/myury/js/vendor/jquery-ui-init.js"></script><script type="text/javascript" src="//ury.org.uk/myury/js/vendor/jquery.themeswitcher.min.js"></script></body></html>

**Comment by AJDurant** [comment]
Fixed by #280
