### ISSUE TITLE
Refactor Show Planner JS

### ISSUE THREAD

**Issue by LloydW93** [UniversityRadioYork/MyRadio#266]
A lot of it has been rewritten and made better in the Bootstrap changes, but it'd be nice to go over this parts that didn't need to be changed and tidy it all up - we can probably remove the dependency on jQuery entirely without much effort.

I don't think this should be included in the bootstrap milestone, hence the separate issue.

**Comment by mstratford** [comment]
Hmm, removing JQuery at this stage would not be the most fun thing, but I can do it if you still really want.

**Comment by LordAro** [comment]
jquery is pretty tightly coupled into the js, and I can't see any particular value in doing so. Closedwontfix
