### ISSUE TITLE
Bootstrapped show planner not displaying entry fields

### ISSUE THREAD

**Issue by adfw** [UniversityRadioYork/MyRadio#341]
As in title. Examining the HTML, we have "div class="well" style="display: hidden;" id="track-manual-entry", so it's clearly not being set to visible. Setting the style to something does make it appear.

**Comment by adfw** [comment]
It looks like Public/js/nipsweb.managelibrary.js:89-98 is responsible for setting it active, but it isn't. One of the tests not holding?

**Comment by adfw** [comment]
Further poking - getElementByID returns null for all id's in the upload modal dialogue - meaning bits of the JS are broken since they rely on it.

**Comment by Flump5281** [comment]
Fixed in bcd308
