### ISSUE TITLE
Limit access when in Obit

### ISSUE THREAD

**Issue by LordAro** [UniversityRadioYork/MyRadio#342]
Limit access to studio IP or the 4 names broadcast ceasers.

Limited to studio IP currently.

Migrated from T183

**Comment by LordAro** [comment]
Every hour, plays the IRN news downloaded locally to the jukebox server

From T17

**Comment by Flump5281** [comment]
I believe these are two seperate issues (badly named, I agree)

1) Limit access to who can trigger Obit to those in the studio or the 4 named broadcast ceasers

2) When obit is enabled, play the news every hour

The second is not a MyRadio issue.
