### ISSUE TITLE
Support for text items in Show Planner

### ISSUE THREAD

**Issue by wlcx** [UniversityRadioYork/MyRadio#350]

**Comment by Flump5281** [comment]
I think this needs revisiting - would people use this functionality? Will BAPS 3 support it?

**Comment by CaptainHayashi** [comment]
BAPS3 will hopefully support it -- it's in the [BAPS3 spec].

[BAPS3 spec]: http://universityradioyork.github.io/baps3-spec/comms/internal/feature-textitems.html

**Comment by LordAro** [comment]
But is it needed/will it be used?

**Comment by CaptainHayashi** [comment]
Well, it has a use--putting hints as to what to say/do between songs between songs.  In the spirit of VISUALISATION(tm), 'if the possibility is there, people might use it'.

also, listd currently supports it
