### ISSUE TITLE
Searching for tracks stops working after the first attempt

### ISSUE THREAD

**Issue by LordAro** [UniversityRadioYork/MyRadio#365]
Noticed on the Jukebox Request page, but apparently been noticed in SP and SIS

1. search for track
2. clear track box
3. search for (different) track
4. observe no results

**Comment by Flump5281** [comment]
https://github.com/UniversityRadioYork/MyRadio/blob/bootstrap/src/Public/js/sis.tracklist.js#L161

works around in SIS
