### ISSUE TITLE
Playlist track search - song can't be found due to limit in dropdown

### ISSUE THREAD

**Issue by AJDurant** [UniversityRadioYork/MyRadio#375]
eg Sing - Ed Sheeran

**Comment by Eiron** [comment]
I would actually prefer a playlist editing system more akin to the way the Show Planner works now. It would be extremely unusual for one to be unable to find a song using that.

**Comment by Eiron** [comment]
This problem is still not fixed, e.g. Believe - Mumford & Sons.

**Comment by LloydW93** [comment]
The problem is fixed in the code base. Whether or not it has been put live on a server is not a bug.

**Comment by LloydW93** [comment]
I just searched for "Believe" and the song appeared in the dropdown.

**Comment by adfw** [comment]
Note that it's currently case-sensitive

**Comment by adfw** [comment]
Hopefully a bit better now thanks to #443

**Comment by Eiron** [comment]
e.g. i - Kendrick Lamar, which previously you might have been able to find by searching for the artist instead of the song title in the 'title' box.

**Comment by LloydW93** [comment]
Creating new issues to track problems created by #441 - #445 and #446
