### ISSUE TITLE
Jukebox connector system broken

### ISSUE THREAD

**Issue by adfw** [UniversityRadioYork/MyRadio#383]
Liquidsoap simply says: "2015/02/25 00:27:18 [request:4] Nonexistent file or ill-formed URI ""!" And nothing more.

**Comment by adfw** [comment]
Timing of the errors beginning corresponds to bootstrap going live

**Comment by adfw** [comment]
Investigated git log for Classes/iTones/* - which actually does the sending of the request - these have only had non-functional changes in the whole bootstrapping process. So it is whatever sends the constructed message before it.
Server is currently running at #379 merge, so nothing resulting from auto-tools #381.

**Comment by Flump5281** [comment]
Configuration issue on server.
