### ISSUE TITLE
Twig API macro should make requests go in AJAX with the right HTTP method

### ISSUE THREAD

**Issue by AJDurant** [UniversityRadioYork/MyRadio#385]

**Comment by LloydW93** [comment]
Can I rename this to "Twig API macro should use APIv2"? :P

**Comment by AJDurant** [comment]
no, that would be a separate thing. This issue is to do with currently if you click the 'revoke permission' link you end up on a json response page.

**Comment by LloydW93** [comment]
That's not what the title of the issue made it sound like at all. It sounded to me like "it just always uses GETs when it should be POSTing"

**Comment by AJDurant** [comment]
I think it does always GET, but the focus of this is making it AJAX
