### ISSUE TITLE
Editing quotes broken

### ISSUE THREAD

**Issue by Flump5281** [UniversityRadioYork/MyRadio#386]
2015-03-01 13:01:33+00[-1] Invalid Quote ID!
#0 /usr/local/www/myradio/src/Controllers/Quotes/editQuote.php(21): MyRadio\ServiceAPI\MyRadio_Quote::getInstance(NULL)
#1 /usr/local/www/myradio/src/Controllers/root_web.php(65): require('/usr/local/www/...')
#2 /usr/local/www/myradio/src/Public/index.php(19): require('/usr/local/www/...')
#3 {main}

**Comment by AJDurant** [comment]
Message: Query failure: SET_SOURCE_SQL
ERROR:  syntax error at or near "SET_SOURCE_SQL"
LINE 1: SET_SOURCE_SQL
             ^
Params: Array
(
    [0] => 8416
    [1] => 190
)

Trace:
```
#0 /usr/local/www/myury-aj/src/Classes/ServiceAPI/MyRadio_Quote.php(267): MyRadio\Database->query('SET_SOURCE_SQL', Array)
#1 /usr/local/www/myury-aj/src/Classes/ServiceAPI/MyRadio_Quote.php(242): MyRadio\ServiceAPI\MyRadio_Quote->set('SET_SOURCE_SQL', 8416)
#2 /usr/local/www/myury-aj/src/Controllers/Quotes/editQuote.php(22): MyRadio\ServiceAPI\MyRadio_Quote->setSource(Object(MyRadio\ServiceAPI\MyRadio_User))
#3 /usr/local/www/myury-aj/src/Controllers/root_web.php(65): require('/usr/local/www/...')
#4 /usr/local/www/myury-aj/src/Public/index.php(19): require('/usr/local/www/...')
#5 {main}
```
