### ISSUE TITLE
rtfm doesn't function correctly without FQ Config::$api_url

### ISSUE THREAD

**Issue by AJDurant** [UniversityRadioYork/MyRadio#400]
with only the base_url and default config value of /api resources are attempted to load over http and are blocked

**Comment by Flump5281** [comment]
Do the comments of Config::$api_url not say it needs to be fully qualified?

**Comment by AJDurant** [comment]
Possibly, but it isn't in Config.php and it isn't defined by the setup
process, so doesn't work ootb

**Comment by Flump5281** [comment]
And I can't make it work ootb if I don't know their full domain, which I currently don't. The API itself works fine, it's just the Swagger aspect.

**Comment by LloydW93** [comment]
APIv2's Swagger now does Things to it works this out.
