### ISSUE TITLE
[sis] Studio selector does not update to reflect change

### ISSUE THREAD

**Issue by wlcx** [UniversityRadioYork/MyRadio#422]
- Click a selection in the SIS studio selector
- Selector changes accordingly
- SIS does not update to reflect the new selection

Additionally, the 'current' selection according to SIS cannot be selected.

**Comment by LloydW93** [comment]
Does Timelord update?

**Comment by wlcx** [comment]
Yes, the select happens fine, it's just the change is not reflected in SIS

**Comment by LloydW93** [comment]
I didn't ask if the select happens! I asked it Timelord updates...

**Comment by wlcx** [comment]
I added an 'and' to the above comment.

**Comment by LloydW93** [comment]
Ah, okay. Hmm.. so they use the same server-side method for polling selector state, so that's interesting.

**Comment by mstratford** [comment]
From what I can see, it only polls the selector state after being clicked (which is somehow broken), however it also doesn't re-poll without setting the selector to see if it has changed.

**Comment by mstratford** [comment]
Fixed here: #663 The "Ready" response wasn't set when changing the state, so SIS didn't update.
