### ISSUE TITLE
Jukebox returning to non-fancy 'default' weightings from midnight to 0100

### ISSUE THREAD

**Issue by Eiron** [UniversityRadioYork/MyRadio#423]
Jukebox is having a nightly retreat to 'old ugly radio' mode, using the old weightings and playlists between 0000-0100. This appears to be the only time this happens. Have gone back over previous nights' scrobbles and it seems consistent.

**Comment by LloydW93** [comment]
Changing field in jukebox.playlist_timeslot from 'time with time zone' to 'time without time zone' seems to have resolved this. Need to update base.sql to reflect.

**Comment by Eiron** [comment]
Playlist weightings shifted themselves back by an hour, except for whatever should have become 2300-0000 because that fell empty. Have corrected all the weighting selections (which may potentially have caused new and exciting problems), but I left a few playlists (with weightings all 0) as I found them to exemplify the issue:

https://ury.org.uk/myradio/iTones/editAvailability/?availabilityid=58
https://ury.org.uk/myradio/iTones/editAvailability/?availabilityid=76
https://ury.org.uk/myradio/iTones/editAvailability/?availabilityid=77
