### ISSUE TITLE
Changes made in database slow to push through to Show Planner

### ISSUE THREAD

**Issue by Eiron** [UniversityRadioYork/MyRadio#447]
Not sure if it only affects songs that have been played, but I updated Tove Lo's 'Talking Body' to 'Talking Body (Clean Love Edit)' and marked it as clean (there are two versions of the track - one edited for radio). It is not clear now, having uploaded the other track, which is which. Both display the explicit track warning when selected, though the clean version is marked as such in the database. It could be it resolves itself in time, but possibly it is something that needs looking into.

**Comment by LloydW93** [comment]
Working as intended. MyRadio caches a lot of information stored in the database.

**Comment by adfw** [comment]
Or, less succinctly, making a change to the DB directly means it doesn't know to refresh the cache. The fix of course being actually providing this functionality to MyRadio.

**Comment by Eiron** [comment]
Is such a functionality likely to be made available? It is still impossible to tell which is the Clean Love and which is the Unclean F*ck version of 'Talking Body'.

**Comment by AJDurant** [comment]
It is planned, as it would be quite useful. @adfw was working on library
management. However the team is pretty busy with other stuff atm.
And it won't update until the cache is cleared for the track.
