### ISSUE TITLE
Method for correcting track information

### ISSUE THREAD

**Issue by Eiron** [UniversityRadioYork/MyRadio#449]
Currently, the only realistic way to update track information (whether it is explicit, repairing an erroneously titled track, fixing a misspelling &c.) is through the Database. It used to be the case that editing the track in the database would fix things pretty quickly in Show Planner, but that does not seem to be the case. Either there needs to be a way to manually bump the cache in these instances, which is not ideal, or there needs to be a way to edit track information from specific tracks without having to go through the database to do it.

(Also, could somebody bump the cache? There are a *heap* of tracks that have been repaired in the past week or so.)

**Comment by LordAro** [comment]
Dup of #354

**Comment by LloydW93** [comment]
Wrt caching, the cache time was increased to 24h once MyRadio was the only thing that interacted with the database in a write context in URY's use case. This is (a) Configurable and (b) Manually purgable using the interface for the configured CacheProvider.
