### ISSUE TITLE
Track Uploader hangs, never completes

### ISSUE THREAD

**Issue by Eiron** [UniversityRadioYork/MyRadio#464]
The track percentage might vary (for me it hangs in the pre-30s), but it seems impossible to upload tracks at the current time.

**Comment by LloydW93** [comment]
Please provide more information about this issue - are there any errors in the console? Can you see the output of the network request that is uploading the track?

I'm also pretty confident that this is going to be an issue with the *servers* hosting MyRadio, whereas GitHub should really only be used to track issues with the MyRadio codebase itself.

**Comment by Eiron** [comment]
POST https://ury.org.uk/myradio/NIPSWeb/upload_central/ net::ERR_CONNECTION_RESET

**Comment by Eiron** [comment]
So yeah, servers, probably. Sorry!

**Comment by LloydW93** [comment]
@adfw Can you please review the server configuration/logs - this sounds like a timeout or upload size limit being exceeded.

**Comment by adfw** [comment]
Blame the sysadmin - I forgot to restart nginx after an update a couple of days ago, which made it behave slightly oddly...
