### ISSUE TITLE
Multiple errors on Profile/view

### ISSUE THREAD

**Issue by LloydW93** [UniversityRadioYork/MyRadio#484]
Notice : Undefined variable: memberid - In /usr/local/www/myradio/src/Classes/ServiceAPI/MyRadio_User.php on line 613
Notice : Undefined variable: memberid - In /usr/local/www/myradio/src/Classes/ServiceAPI/MyRadio_User.php on line 545
Notice : Undefined variable: memberid - In /usr/local/www/myradio/src/Classes/ServiceAPI/MyRadio_User.php on line 545
Warning : in_array() expects parameter 2 to be array, null given - In /usr/local/www/myradio/src/Classes/ServiceAPI/MyRadio_APICaller_Common.php on line 30

**Comment by AJDurant** [comment]
fixed at some point
