### ISSUE TITLE
Add mark paid checkbox to add member form

### ISSUE THREAD

**Issue by wlcx** [UniversityRadioYork/MyRadio#502]

**Comment by LloydW93** [comment]
That should happen a few minutes later anyway through member sync?

**Comment by wlcx** [comment]
Mainly for when they’ve paid in cash by the sounds of it


On 2 October 2015 at 14:39:55, Lloyd Wallis (notifications@github.com) wrote:

That should happen a few minutes later anyway through member sync?

**Comment by LloydW93** [comment]
Management should still be updating the YUSU backpages too - that's the number that's used for releasing grant, after all
