### ISSUE TITLE
Move external Timelord dependencies onto MyRadio host webserver.

### ISSUE THREAD

**Issue by adfw** [UniversityRadioYork/MyRadio#504]
'new' timelord boxen (e.g. with the pi's) do not have an external network connection (without a proxy anyway), so external sources (such as the font Source Sans Pro, the only thing currently) do not load.

**Comment by LloydW93** [comment]
Do you still even want Timelord in MyRadio directly?

**Comment by ChrisTheBaron** [comment]
Can this be closed now @adfw?

**Comment by LordAro** [comment]
closedwontfix

(use node-timelord instead)
