### ISSUE TITLE
Support PHP 7

### ISSUE THREAD

**Issue by LloydW93** [UniversityRadioYork/MyRadio#526]
http://php.net/manual/en/migration70.incompatible.php
- [x] Validate use of indirect variables/properties/methods (e.g. $$thing)
- [x] Foreaches by-reference where necessary
- [x] Use of mcrypt aliases
- [x] Fixes to Custom Session Handler Return Values

**Comment by GrahamCampbell** [comment]
> Use of mcrypt aliases

Mcrypt is deprecated. I'd recommend migrating to a currently maintained library like openssl.
