### ISSUE TITLE
Break up CoreUtils into functional areas

### ISSUE THREAD

**Issue by AJDurant** [UniversityRadioYork/MyRadio#54]
for example redirect, back, etc. into a class for browser manipulation.

**Comment by LordAro** [comment]
For whatever reason, I'm looking into this. Suggested names for the split classes?

**Comment by Flump5281** [comment]
The name of the the functional group plus "Utils" should do, e.g. TimeUtils is the immediate thing I can think of that has a lot of functions of the same type.
