### ISSUE TITLE
Automatic 'Get Involved' email comes from `no-reply` 

### ISSUE THREAD

**Issue by ChrisTheBaron** [UniversityRadioYork/MyRadio#574]
People are trying to reply to it, and failing (obviously)

**Comment by LordAro** [comment]
...that's their own fault?

**Comment by AJDurant** [comment]
Pretty sure there is already an issue mentioning this

**Comment by ChrisTheBaron** [comment]
@LordAro I know it's their own fault, but the welcome email is worded to make it seem like it was sent by a person. I raised the issue with committee and we decided to make a second email that contains their account details, and have the first email come from `station.manager`

**Comment by AJDurant** [comment]
Duplicate of #108
