### ISSUE TITLE
Attempting to leave demo before signing presenter contract results in permission error

### ISSUE THREAD

**Issue by LordAro** [UniversityRadioYork/MyRadio#575]
`I'm sorry, but you don't have permission to go here.`

**Comment by AJDurant** [comment]
You know there is an interface for adding action permission in MyRadio. Scheduler/leaveDemo just needed the GLOBAL ACCESS permission like the rest of the demo actions...

**Comment by LordAro** [comment]
OK fine, but does this need adding to the initial schema import?

**Comment by AJDurant** [comment]
Yeah, I don't know how up to date any of that is though. Last time I ran setup it was missing quite a bit

**Comment by LordAro** [comment]
:(
