### ISSUE TITLE
Add link to URY website in MyRadio navbar

### ISSUE THREAD

**Issue by ChrisTheBaron** [UniversityRadioYork/MyRadio#583]
Something like this would be nice:

![pasted image at 2016_10_20 19_49](https://cloud.githubusercontent.com/assets/6439999/19573507/7027deb6-96fe-11e6-84c2-2ce0f5a71724.png)

**Comment by TomBellis** [comment]
Would it go in: MyRadio/src/Templates/parts/nav.twig

**Comment by LordAro** [comment]
I'd think so, but it'd want to be configurable (from php's config file) as well
Which'll make it a bit more fun

**Comment by TomBellis** [comment]
@LordAro not too familiar with php. What do you mean by configurable?

**Comment by TomBellis** [comment]
So can we add:  
`<a class="navbar-brand" href="//ury.org.uk/">ury.org.uk</a>`
to the 
`MyRadio/src/Templates/parts/nav.twig`

**Comment by AJDurant** [comment]
The url is in the config and should be read from there. I can't remember how you do that from Twig

**Comment by Brookke** [comment]
I am confused, why would it be hard coded that the link title is ury.org.uk when the href should be set in config? If the href was to change to ury.radio wouldn't the link title want to change too?

**Comment by AJDurant** [comment]
the url is already in the config file
