### ISSUE TITLE
Add member id to any drop-down that lists members

### ISSUE THREAD

**Issue by ChrisTheBaron** [UniversityRadioYork/MyRadio#592]
This will eliminate issues like https://github.com/UniversityRadioYork/Issues/issues/56 and https://github.com/UniversityRadioYork/MyRadio/issues/588 where people are selecting the wrong users.

So the drop-downs would look like:
- Testy McTesterson (#123123)
- Testy McTesterson (#34564)

And people would be able to tell the difference (in theory)

**Comment by LloydW93** [comment]
I disagree with this on the grounds of it being pretty poor UX - there must be something better we can do here.

e.g. 
- Add a property to the field type that limits it to current/paid/presenter
- Display 'eduroam' field when there's multiple
- Merge into one option in the drop down, then if selected open a modal with information about each
- Display profile photo
- "Sort" by relation to current user

**Comment by ChrisTheBaron** [comment]
> Add a property to the field type that limits it to current/paid/presenter

Doesn't guarantee elimination of duplicates.

> Display 'eduroam' field when there's multiple

This is a possible solution, except non-students have eduroam as `null`. Also I would go for showing it against every user to keep it consistent.

> Merge into one option in the drop down, then if selected open a modal with information about each

IMO that's even worse UX, the user won't be expecting a modal window when selecting something from a drop-down.

> Display profile photo

We'd have to redo the entire UI to show them at any reasonable size, plus loading times.

> "Sort" by relation to current user

Again doesn't guarantee elimination of duplicates.

**Comment by ChrisTheBaron** [comment]
Summons @LordAro & @Brookke for their thoughts

**Comment by Brookke** [comment]
for the non eduroam users how do they login? Can we use usernames?

**Comment by LordAro** [comment]
^ That's the question, I'm seeing 1359 members with null eduroam, and most of those are missing local_aliases as well, which would've been my second guess for what's used as a username.

But I agree, eduroam (or some arbitrary `username` thing) would be preferential to memberid

**Comment by mstratford** [comment]
I can work on this if you want, maybe I can put eduroam, with ID for fallover?

**Comment by LordAro** [comment]
Seems reasonable, maybe go eduroam -> local_alias? Since that's what they'll be using to login if they don't have an eduroam entry

**Comment by mstratford** [comment]
Sure, but just to check, is there any issues with not being able to tell if it is eduroam or local_alias?

**Comment by LordAro** [comment]
Not sure what you mean?

**Comment by mstratford** [comment]
I’m just wondering, in some cases, eduroam and local-alias may have a similar format, so you wouldn’t be able to tell if it was displaying eduroam or local-alias. Is this a problem?

**Comment by LordAro** [comment]
Not sure why it would be, they're always going to be unique, regardless (or at the very least, should be)

**Comment by mstratford** [comment]
It works :)

\o/
 I
/ \
