### ISSUE TITLE
No API endpoint for Today's Schedule.

### ISSUE THREAD

**Issue by mstratford** [UniversityRadioYork/MyRadio#601]
Any chance /timeslots/ can have an endpoint that gives the schedule for today (start time, end time, title, URL, short description if those exist, img thumb url) for 2016-site? 

In this case, if it could be optionally limited to current show onwards, that would be great!

**Comment by AJDurant** [comment]
Can't you just filter on the week? ury.ajsdf.co.uk/schedule does client
side filtering on the week->day view

**Comment by mstratford** [comment]
I was thinking that, how does SIS do it?

Also, I’ve not seen that site before, is that using the API or similar to how 2013 does it? :)

**Comment by AJDurant** [comment]
SIS does stuff internally, but it just calls getCurrentAndNext with an n
value of 10. That is a reference use of the API, I wrote it over a year ago
when developing the missing functionality in the API.

**Comment by LloydW93** [comment]
Is the conclusion that this isn't wanted? If so, we can close this. If not, assign it to yourself and do it :P

**Comment by mstratford** [comment]
Well, if getCurrentAndNext can provide me a fixed number of upcoming stuff, then this can be closed, so I'll close it :)
