### ISSUE TITLE
Setting an Intro doesn't bust the cache for a TimeslotItem

### ISSUE THREAD

**Issue by LloydW93** [UniversityRadioYork/MyRadio#612]
NIPSWeb_TimeslotItem currently stores the $item object itself within it. This means that for the lifetime of the TimeslitItem, changes to the Track are not propagated. This should probably store a type/id pair here, and have the actual object for using in a property that doesn't get cached.

**Comment by mstratford** [comment]
This is still a problem I think, setting into in Showplanner updates the edit track form, but not the show planner after reload?

**Comment by LloydW93** [comment]
Never said it was fixed :)
