### ISSUE TITLE
Officer positions getting hidden when vacant

### ISSUE THREAD

**Issue by LordAro** [UniversityRadioYork/MyRadio#655]
Stood down a HoP just this week, but the vacant position did not appear on the officer page, as I expected it to. Same happened when I did the same for AssProd.

**Comment by AJDurant** [comment]
There was some fancy SQL that managed this, did you break it in your 'no functional changes' commit?

**Comment by LordAro** [comment]
Heh, quite possibly!
No php errors on the page though, so it's not that

**Comment by AJDurant** [comment]
Yes you did. 
https://github.com/UniversityRadioYork/MyRadio/commit/8036a861a84edc4e1a1e070ad0e9c684915c23e8#diff-dc797ab14ffc52923c3dedc6056482eeR142
When you do these, they are *only* supposed to be formatting. If you start changing actual code then it's never going to get reviewed.
