### ISSUE TITLE
Support PHP 7.1

### ISSUE THREAD

**Issue by LloydW93** [UniversityRadioYork/MyRadio#668]
#526 is done, but what actually got deployed this week is 7.1 (yes, I edited the issue title of the original).

7.1 introduces backwards incompatible changes which we should review (an initial look seems fine), "other changes" which are in fact also backwards incompatible (Show Planner broke), and a set of new warnings for upcoming deprecations and general strictness that need to go away.

**Comment by LordAro** [comment]
http://php.net/manual/en/migration71.incompatible.php link for helpfulness

**Comment by LordAro** [comment]
I believe we've got all these now. Anyone noticed anything else?
@mstratford @LloydW93

**Comment by mstratford** [comment]
I don't think I've seen any warnings in a while.

**Comment by mstratford** [comment]
There's one while editing banners, but we're working on this already.

**Comment by mstratford** [comment]
Also one in Charts.

**Comment by LordAro** [comment]
```
Warning : Declaration of MyRadio\ServiceAPI\MyRadio_Banner::create(MyRadio\ServiceAPI\MyRadio_Photo $photo, $alt = 'Unnamed Ba...', $target = NULL, $type = 2) should be compatible with MyRadio\ServiceAPI\MyRadio_Photo::create($tmp_file) - In /usr/local/www/myradio/src/Classes/ServiceAPI/MyRadio_Banner.php on line 19
```

```
Unknown error code : Non-static method MyRadio\ServiceAPI\MyRadio_ChartType::getAll() should not be called statically - In /usr/local/www/myradio/src/Controllers/Charts/default.php on line 9
```

For reference porpoises. Fairly sure the second on is not new

**Comment by LordAro** [comment]
Fixed
