### ISSUE TITLE
Adding permissions doesn't kick cache.

### ISSUE THREAD

**Issue by mstratford** [UniversityRadioYork/MyRadio#728]

**Comment by TomBellis** [comment]
Added the permission to view webcams to the role of Assistant Head of Audio Resources and this has not appeared...

**Comment by LordAro** [comment]
It's supposed to... https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Classes/ServiceAPI/MyRadio_Officer.php#L540

**Comment by AJDurant** [comment]
The user needs to log out and in. We could forcibly kill the session, but that would be a bad experience if they are in the middle of something.

**Comment by LordAro** [comment]
Not a lot we can do about this one, closedwontfix

**Comment by mstratford** [comment]
Maybe just a message indicating they must re-login...
