### ISSUE TITLE
Remove "report faults" email option

### ISSUE THREAD

**Issue by markspolakovs** [UniversityRadioYork/MyRadio#822]
No point having another one, just use #studio-faults in Slack.

**Comment by mstratford** [comment]
Hmm, it's not doing any harm, plus not every 100% of people have slack.

**Comment by markspolakovs** [comment]
@mstratford respectfully disagreed - not everyone will check their URY emails, so a fault report via email may go without follow-up - we should get as many people on Slack as possible imo

**Comment by LordAro** [comment]
Unless something's changed, everyone should be checking their emails.
People should not be expected to be checking, or indeed be on, slack.

Email has always been URY's primary method of communication, as it is
something *everyone* has.

**Comment by markspolakovs** [comment]
What's changed is that the spam filter has become non-functional, so 90% of URY email we get is spam. This lead to people asking for roundcube inboxes just to stem the flow of spam, implication being that they'll ignore them.

**Comment by markspolakovs** [comment]
Also, Roundcube is a pain in the arse and doesn't send push notifications, which isn't ideal when someone's messaging you about a studio fault. Slack does.

**Comment by LordAro** [comment]
Sounds like treating the symptoms, not the cause. Fix the spam filter.

**Comment by markspolakovs** [comment]
I'd love to, believe me.
