### ISSUE TITLE
Send new officers an email

### ISSUE THREAD

**Issue by markspolakovs** [UniversityRadioYork/MyRadio#838]
Requested by management - essentially send new officers an email explaining some things about their role, wiki, email etc. (I have a draft text, can provide it if needed).

Questions:
 * Emailing every new elected person on every role change will be a bit much, perhaps we limit it somehow? (Maybe "if they haven't held a committee position in x months"?)

**Comment by AJDurant** [comment]
The content of this email back in 2013/14 was:

> Hello,
> 
> Congratulations in being elected to the URY Committee! If you have been a member of the committee before, then you might now some of this stuff, but bear with me...
> 
> -- New buttons
>     When you next log onto MyURY, you will probably find that you have some new buttons, or some more options on some pages. 
>     These come free* with your new position, but if you think you should have something that you don't drop an email to computing (computing@ury.org.uk) and we can check.
> 
> -- e-mail
>     You will now automatically have email for certain mailing lists (such as officers@ury.org.uk) and aliases (e.g. station.cat@ury.org.uk or head.of.cabbage@ury.org.uk) sent to your e-mail address.
>     As a member of the committee, you can request a URY email address (firstname.lastname@ury.org.uk). Just ask a member of computing team (computing@ury.org.uk) if you would like one.
> 
> -- Extra Training
>     If you are new or just a bit unsure about anything (maybe you'd like to be able to use Studio 2 to it's full potential) then don't hesitate to ask someone, Heads of Team should know what they are doing but if not (or you are a head of team) then ask a friendly engineer or our presenting team for some training. Obviously for help with any Computing Service then contact us!
> 
> -- Reporting Problems / Faults
>     As with all members, please report any problems / faults to the relevant people, that's us (Computing) for any computery issue, engineering@ury.org.uk for any studio/fixtures/fittings problem, or faults@ury.org.uk for anything that could be both or you just aren't sure. This is the best way of contacting the teams as many on them are not on Facebook / don't check it regularly, it allows us to track and work on fixing your issue a lot more easily, and it will instantly reach the whole team.
> 
> 
> I think that's all, just ask if you have any questions! Cheers
> 
> 
> *With new buttons comes new responsibility!
> 
> 
> PS. if you are an old officer that hasn't been elected, you will still receive your officer emails for the next 20 days.
> 
> -- 
> URY Computing Team

**Comment by markspolakovs** [comment]
For completeness, here's the draft that past management gave me:

> Hi!
>
> Welcome to your new URY officership! Congratulations (even if RON was your only opponent in a vote).
>
> There are some things you should know. Firstly, if you find that you're being bombarded with emails to your University account, you can set up a roundcube email (like a special URY inbox) by dropping a message in #computing on Slack. You'll also need to set up an identity in this email, which can be done by heading to settings, then adding an identity and changing your email to your relevant URY role (e.g. head.of.speech@ury.org.uk)
>
> Whilst we're talking about Slack, try and keep discussions (especially in bigger message boards such as #general) to threads of their related topic, so that newcomers to a conversation can pick it back up easily. You can do this by hovering over a message and clicking “start a thread” rather than just commenting in the channel below it.
>
> If you have any questions about URY or your role, they should be covered in the [URY wiki](https://ury.org.uk/wiki) and [constitution](https://ury.org.uk/wiki/Constitution)
>
> Finally, for any event you're thinking of putting on, there is an Events guide here *insert when done*. The vital points to note are that you need to get the Secretary to put in an EMF, and that the Chief Engineer, Head of Computing, and Production Manager should have given the go ahead for this event as without their support it will be impossible!
>
> Always remember that at URY everyone wants the best for the station and that we work as a team - if you need anything or have any concerns, just say!
>
> See you soon,
> [station manager's name]

**Comment by markspolakovs** [comment]
@AJDurant Actually... you mention this email existed in 2013/14, do you know why it was removed / isn't a thing anymore?

**Comment by AJDurant** [comment]
It was never automated, just someone from computing wrote and sent the email when the elections were finished, normally whilst sitting in the bar with everyone...

I sent that one which is why it was relatively easy to find, but I would have received a number of others. As to why it didn't continue, probably the practise of doing it was forgotten one year and never passed on. Automating it though MyRadio on officership assignment sounds like a good plan though.

**Comment by AJDurant** [comment]
It might have been that at one stage the station manager sent it instead of computing, so it wasn't passed on like that.
